public let allRegisters: [ComponentRegister] = [
  ButtonComponentRegister(),
  ContainerComponentRegister(),
  DescriptionComponentRegister(),
  ExampleComponentRegister(),
  GenericListItemComponentRegister(),
  ImageComponentRegister(),
  ProgressStepperComponentRegister(),
  SectionTitleComponentRegister(),
  SegmentedControlComponentRegister(),
  SelectionCardComponentRegister(),
  SeparatorComponentRegister(),
  SpacerComponentRegister(),
  TextComponentRegister(),
  WelcomeComponentRegister(),
]
